version: '3.8'
services:
  web:
    build:
      context: .././app
      dockerfile: Dockerfile.${ENV}
    expose:
      - ${PROJECT_PORT}
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - .env.${ENV}
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:latest
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data/
    expose:
      - ${POSTGRES_PORT}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}' ]
      interval: 10s
      timeout: 60s
      retries: 10
    env_file:
      - .env.${ENV}
  nginx:
    build: ../nginx
    ports:
      - '${NGINX_PORT}:${NGINX_PORT}'
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: